### ISSUE TITLE
Rostime algorithm errors

### ISSUE THREAD

**Issue by stonier** [ros-windows/win_ros#15]
https://github.com/ros/ros_comm/issues/160

**Comment by stonier** [comment]
- Download his zipped standalone test code
- Compare with current winros code in rostime
- If it's the same code, then
  - Compile and execute
  - If reproducible, debug.

**Comment by yichoe** [comment]
Time::now() returns `g_sim_time` as well as throws TimeNotInitializedException unless Time::init() is called. Since 'straszheim'  didn't call Time::init(), ros_walltime() wouldn't be executed.

When we call Time::now() after calling Time::init(), the second part is updated well.

I wonder how straszheim got the result using MSVC.

**Comment by stonier** [comment]
`time::init()` gets called in ros::init(), so it should be called.

Conclusion - we can't reproduce.

**Comment by stonier** [comment]
Made a recommendation to close the issue on ros_comm.

**Comment by yichoe** [comment]
PS: Although `ros::init()` is called, TimeNotInitializedException is raised. In ros::init(), Time::init() does not appear as well.

**Comment by stonier** [comment]
Just checked - you are right. Instead it gets called the first time a `Nodehandle` is constructed (libros/init.cpp -> libros/NodeHandle.cpp).
